"use strict";(self.webpackChunkx_markdown_mini_docs=self.webpackChunkx_markdown_mini_docs||[]).push([[823],{27752:function(a,i,_){_.r(i);var d=_(72269),m=_(93359),h=_(61788),u=_(19977),x=_(78003),o=_(2676),c=_(96057),g=_(83213),s=_(53683),t=_(64389),l=_(67294),e=_(14038),n=_(85893);function r(){return(0,n.jsx)(s.dY,{children:(0,n.jsx)(l.Suspense,{fallback:(0,n.jsx)(t.Z,{}),children:(0,n.jsxs)(n.Fragment,{children:[(0,n.jsxs)("div",{className:"markdown",children:[(0,n.jsxs)("h1",{id:"code-highlight",children:[(0,n.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-highlight",children:(0,n.jsx)("span",{className:"icon icon-link"})}),"Code Highlight"]}),(0,n.jsxs)("p",{children:[(0,n.jsx)("code",{children:e.texts[0].value}),e.texts[1].value,(0,n.jsx)("code",{children:e.texts[2].value}),e.texts[3].value]}),(0,n.jsxs)("h2",{id:"introduce",children:[(0,n.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#introduce",children:(0,n.jsx)("span",{className:"icon icon-link"})}),"Introduce"]}),(0,n.jsx)(o.Z,{lang:"ts",children:e.texts[4].value}),(0,n.jsxs)("h2",{id:"code-sample",children:[(0,n.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-sample",children:(0,n.jsx)("span",{className:"icon icon-link"})}),"Code sample"]})]}),(0,n.jsx)(s.Dl,{demo:{id:"docs-docs-plugins-code-highlight-demo-codehighlightdemo"},previewerProps:{filename:"src/demos/plugins/CodeHighlightDemo.tsx"}}),(0,n.jsxs)("div",{className:"markdown",children:[(0,n.jsx)("p",{children:e.texts[5].value}),(0,n.jsxs)("h2",{id:"custom-languages",children:[(0,n.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#custom-languages",children:(0,n.jsx)("span",{className:"icon icon-link"})}),"Custom languages"]}),(0,n.jsx)(o.Z,{lang:"ts",children:e.texts[6].value})]})]})})})}i.default=r},14038:function(a,i,_){_.r(i),_.d(i,{texts:function(){return d}});const d=[{value:"CodeHighlight",paraId:0,tocIndex:0},{value:" uses ",paraId:0,tocIndex:0},{value:"highlight.js",paraId:0,tocIndex:0},{value:" to take over fenced code blocks. Blocks without a language, or with an unknown one, fall back to the built-in plain code renderer. The plugin is opt-in, so pages that do not register it keep the lean default path.",paraId:0,tocIndex:0},{value:`import { XMarkdownMini } from '@ant-design/x-markdown-mini';
import CodeHighlight from '@ant-design/x-markdown-mini/plugins/CodeHighlight';
`,paraId:1,tocIndex:1},{value:"Registered by default: JavaScript, TypeScript, Python, Java, CSS, XML, JSON, SQL, Bash, Shell, C, C++, Go, Rust, YAML, Markdown, Diff, Plaintext.",paraId:2},{value:`import python from 'highlight.js/lib/languages/python';
import CodeHighlight from '@ant-design/x-markdown-mini/plugins/CodeHighlight';

CodeHighlight({
  languages: { python },
  hljsOptions: { ignoreIllegals: true },
});
`,paraId:3,tocIndex:3}]}}]);
