"use strict";(self.webpackChunkx_markdown_mini_docs=self.webpackChunkx_markdown_mini_docs||[]).push([[541],{20628:function(o,_,d){d.r(_);var a=d(72269),x=d(93359),m=d(61788),u=d(19977),c=d(78003),s=d(2676),h=d(96057),v=d(83213),t=d(53683),i=d(64389),r=d(67294),n=d(3963),e=d(85893);function l(){return(0,e.jsx)(t.dY,{children:(0,e.jsx)(r.Suspense,{fallback:(0,e.jsx)(i.Z,{}),children:(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h1",{id:"formula",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#formula",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Formula"]}),(0,e.jsxs)("p",{children:[n.texts[0].value,(0,e.jsx)("code",{children:n.texts[1].value}),n.texts[2].value,(0,e.jsx)("code",{children:n.texts[3].value}),n.texts[4].value]}),(0,e.jsxs)("h2",{id:"introduce",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#introduce",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Introduce"]}),(0,e.jsx)(s.Z,{lang:"ts",children:n.texts[5].value}),(0,e.jsxs)("h2",{id:"code-sample",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-sample",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Code sample"]}),(0,e.jsxs)("p",{children:[n.texts[6].value,(0,e.jsx)("code",{children:n.texts[7].value}),n.texts[8].value,(0,e.jsx)("code",{children:n.texts[9].value}),n.texts[10].value,(0,e.jsx)("code",{children:n.texts[11].value}),n.texts[12].value,(0,e.jsx)("code",{children:n.texts[13].value}),n.texts[14].value]})]}),(0,e.jsx)(t.Dl,{demo:{id:"docs-docs-plugins-latex-demo-latexdemo"},previewerProps:{filename:"src/demos/plugins/LatexDemo.tsx"}}),(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h2",{id:"error-handling",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#error-handling",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Error handling"]}),(0,e.jsxs)("p",{children:[n.texts[15].value,(0,e.jsx)("code",{children:n.texts[16].value}),n.texts[17].value,(0,e.jsx)("code",{children:n.texts[18].value}),n.texts[19].value]}),(0,e.jsx)(s.Z,{lang:"ts",children:n.texts[20].value})]})]})})})}_.default=l},3963:function(o,_,d){d.r(_),d.d(_,{texts:function(){return a}});const a=[{value:"The ",paraId:0,tocIndex:0},{value:"Latex",paraId:0,tocIndex:0},{value:" plugin uses KaTeX to convert inline and block formulas into ",paraId:0,tocIndex:0},{value:"MiniNode[]",paraId:0,tocIndex:0},{value:". The plugin only generates nodes; import the stylesheet separately (see the style file in the demo).",paraId:0,tocIndex:0},{value:`import { XMarkdownMini } from '@ant-design/x-markdown-mini';
import Latex from '@ant-design/x-markdown-mini/plugins/Latex';
`,paraId:1,tocIndex:1},{value:"Supports the ",paraId:2,tocIndex:2},{value:"$...$",paraId:2,tocIndex:2},{value:", ",paraId:2,tocIndex:2},{value:"$$...$$",paraId:2,tocIndex:2},{value:", ",paraId:2,tocIndex:2},{value:"\\(...\\)",paraId:2,tocIndex:2},{value:" and ",paraId:2,tocIndex:2},{value:"\\[...\\]",paraId:2,tocIndex:2},{value:" delimiters.",paraId:2,tocIndex:2},{value:"With ",paraId:3,tocIndex:3},{value:"throwOnError: false",paraId:3,tocIndex:3},{value:", a broken formula renders as its source text; use ",paraId:3,tocIndex:3},{value:"onError",paraId:3,tocIndex:3},{value:" to emit custom error nodes instead:",paraId:3,tocIndex:3},{value:`Latex({
  onError: (tex, err) => [
    {
      name: 'text',
      attrs: { value: \`[formula error: \${err.message}]\` },
    },
  ],
});
`,paraId:4,tocIndex:3}]}}]);
