"use strict";(self.webpackChunkx_markdown_mini_docs=self.webpackChunkx_markdown_mini_docs||[]).push([[90],{93596:function(s,_,a){a.r(_);var d=a(72269),l=a(93359),u=a(61788),x=a(19977),c=a(78003),i=a(2676),h=a(96057),v=a(83213),t=a(53683),o=a(64389),r=a(67294),n=a(2813),e=a(85893);function m(){return(0,e.jsx)(t.dY,{children:(0,e.jsx)(r.Suspense,{fallback:(0,e.jsx)(o.Z,{}),children:(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h1",{id:"animation",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#animation",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Animation"]}),(0,e.jsx)("p",{children:n.texts[0].value}),(0,e.jsxs)("h2",{id:"introduce",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#introduce",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Introduce"]}),(0,e.jsxs)("p",{children:[n.texts[1].value,(0,e.jsx)("code",{children:n.texts[2].value}),n.texts[3].value,(0,e.jsx)("code",{children:n.texts[4].value}),n.texts[5].value]}),(0,e.jsx)(i.Z,{lang:"ts",children:n.texts[6].value}),(0,e.jsxs)("h2",{id:"code-sample",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-sample",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Code sample"]})]}),(0,e.jsx)(t.Dl,{demo:{id:"docs-docs-animation-demo-animation"},previewerProps:{filename:"src/demos/streaming/Animation.tsx"}}),(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("p",{children:[n.texts[7].value,(0,e.jsx)("code",{children:n.texts[8].value}),n.texts[9].value,(0,e.jsx)("code",{children:n.texts[10].value}),n.texts[11].value,(0,e.jsx)("code",{children:n.texts[12].value}),n.texts[13].value]}),(0,e.jsx)(i.Z,{lang:"css",children:n.texts[14].value}),(0,e.jsxs)("p",{children:[n.texts[15].value,(0,e.jsx)("code",{children:n.texts[16].value}),n.texts[17].value]})]})]})})})}_.default=m},2813:function(s,_,a){a.r(_),a.d(_,{texts:function(){return d}});const d=[{value:"Streaming animation marks only newly emitted block nodes for a light fade-in during AI output. It does not reflow committed content or replay when stable blocks are reused.",paraId:0,tocIndex:0},{value:"Enable ",paraId:1,tocIndex:1},{value:"enableAnimation",paraId:1,tocIndex:1},{value:" in the render config, then define ",paraId:1,tocIndex:1},{value:"md-animate-block",paraId:1,tocIndex:1},{value:" in the mini-program stylesheet:",paraId:1,tocIndex:1},{value:`streaming: { hasNextChunk: true, enableAnimation: true }
`,paraId:2,tocIndex:1},{value:"When ",paraId:3},{value:"enableAnimation: true",paraId:3},{value:", every block-level node gets ",paraId:3},{value:"md-animate-block",paraId:3},{value:" appended to its ",paraId:3},{value:"class",paraId:3},{value:". In your mini-program WXSS / ACSS file:",paraId:3},{value:`.md-animate-block {
  animation: md-fade-in 240ms ease-out both;
}
@keyframes md-fade-in {
  from {
    opacity: 0;
    transform: translateY(2px);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
`,paraId:4},{value:"The CSS animation runs once when a node first appears \u2014 after subsequent commits push it into ",paraId:5},{value:"stableNodes",paraId:5},{value:", its reference stays the same and the animation does not replay.",paraId:5}]}}]);
