"use strict";(self.webpackChunkx_markdown_mini_docs=self.webpackChunkx_markdown_mini_docs||[]).push([[823],{27752:function(a,d,n){n.r(d);var i=n(72269),m=n(93359),u=n(61788),h=n(19977),c=n(78003),s=n(2676),g=n(96057),x=n(83213),o=n(53683),t=n(64389),l=n(67294),_=n(14038),e=n(85893);function r(){return(0,e.jsx)(o.dY,{children:(0,e.jsx)(l.Suspense,{fallback:(0,e.jsx)(t.Z,{}),children:(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h1",{id:"code-highlight",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-highlight",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Code Highlight"]}),(0,e.jsxs)("p",{children:[(0,e.jsx)("code",{children:_.texts[0].value}),_.texts[1].value,(0,e.jsx)("code",{children:_.texts[2].value}),_.texts[3].value]}),(0,e.jsxs)("h2",{id:"introduce",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#introduce",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Introduce"]}),(0,e.jsx)(s.Z,{lang:"ts",children:_.texts[4].value}),(0,e.jsxs)("h2",{id:"code-sample",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-sample",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Code sample"]})]}),(0,e.jsx)(o.Dl,{demo:{id:"docs-docs-plugins-code-highlight-demo-codehighlightdemo"},previewerProps:{filename:"src/demos/plugins/CodeHighlightDemo.tsx"}}),(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsx)("p",{children:_.texts[5].value}),(0,e.jsxs)("h2",{id:"custom-languages",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#custom-languages",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Custom languages"]}),(0,e.jsx)(s.Z,{lang:"ts",children:_.texts[6].value})]})]})})})}d.default=r},14038:function(a,d,n){n.r(d),n.d(d,{texts:function(){return i}});const i=[{value:"CodeHighlight",paraId:0,tocIndex:0},{value:" uses ",paraId:0,tocIndex:0},{value:"highlight.js",paraId:0,tocIndex:0},{value:" to take over fenced code blocks. Blocks without a language, or with an unknown one, fall back to the built-in plain code renderer. The plugin is opt-in, so pages that do not register it keep the lean default path.",paraId:0,tocIndex:0},{value:`import { XMarkdownMini } from '@ant-design/x-markdown-mini';
import CodeHighlight from '@ant-design/x-markdown-mini/plugins/CodeHighlight';
`,paraId:1,tocIndex:1},{value:"Registered by default: JavaScript, TypeScript, Python, Java, CSS, XML, JSON, SQL, Bash, Shell, C, C++, Go, Rust, YAML, Markdown, Diff, Plaintext.",paraId:2},{value:`import python from 'highlight.js/lib/languages/python';
import CodeHighlight from '@ant-design/x-markdown-mini/plugins/CodeHighlight';

CodeHighlight({
  languages: { python },
  hljsOptions: { ignoreIllegals: true },
});
`,paraId:3,tocIndex:3}]}}]);
