"use strict";(self.webpackChunkx_markdown_mini_docs=self.webpackChunkx_markdown_mini_docs||[]).push([[519],{15946:function(i,_,n){n.r(_);var a=n(72269),u=n(93359),c=n(61788),m=n(19977),h=n(78003),d=n(2676),x=n(96057),v=n(83213),t=n(53683),r=n(64389),o=n(67294),s=n(43918),e=n(85893);function l(){return(0,e.jsx)(t.dY,{children:(0,e.jsx)(o.Suspense,{fallback:(0,e.jsx)(r.Z,{}),children:(0,e.jsxs)(e.Fragment,{children:[(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("h1",{id:"typewriter-mode",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#typewriter-mode",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Typewriter Mode"]}),(0,e.jsx)("p",{children:s.texts[0].value}),(0,e.jsxs)("h2",{id:"introduce",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#introduce",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Introduce"]}),(0,e.jsxs)("p",{children:[s.texts[1].value,(0,e.jsx)("code",{children:s.texts[2].value}),s.texts[3].value]}),(0,e.jsx)(d.Z,{lang:"ts",children:s.texts[4].value}),(0,e.jsxs)("h2",{id:"code-sample",children:[(0,e.jsx)("a",{"aria-hidden":"true",tabIndex:"-1",href:"#code-sample",children:(0,e.jsx)("span",{className:"icon icon-link"})}),"Code sample"]})]}),(0,e.jsx)(t.Dl,{demo:{id:"docs-docs-typewriter-demo-typewriter"},previewerProps:{filename:"src/demos/streaming/Typewriter.tsx"}}),(0,e.jsxs)("div",{className:"markdown",children:[(0,e.jsxs)("p",{children:[s.texts[5].value,(0,e.jsx)("code",{children:s.texts[6].value}),s.texts[7].value,(0,e.jsx)("code",{children:s.texts[8].value}),s.texts[9].value]}),(0,e.jsx)(d.Z,{lang:"ts",children:s.texts[10].value}),(0,e.jsxs)("p",{children:[s.texts[11].value,(0,e.jsx)("code",{children:s.texts[12].value}),s.texts[13].value,(0,e.jsx)("strong",{children:s.texts[14].value}),s.texts[15].value]})]})]})})})}_.default=l},43918:function(i,_,n){n.r(_),n.d(_,{texts:function(){return a}});const a=[{value:"Typewriter mode is for visible character-by-character output. It reuses the streaming processor, adding delays between semantic chunks and characters.",paraId:0,tocIndex:0},{value:"Configure delimiters, inter-chunk delay, and per-character delay under ",paraId:1,tocIndex:1},{value:"streaming.semantic",paraId:1,tocIndex:1},{value:":",paraId:1,tocIndex:1},{value:`streaming: { semantic: true }
`,paraId:2,tocIndex:1},{value:"When either ",paraId:3},{value:"chunkDelay",paraId:3},{value:" or ",paraId:3},{value:"charDelay",paraId:3},{value:' is > 0, the processor steps through semantic chunks one at a time. Each step runs one "commit + tail re-parse + onPatch" cycle.',paraId:3},{value:`streaming: {
  semantic: {
    delimiters: /[\u3002\uFF01\uFF1F\\n]/,
    maxChunkSize: 60,
    chunkDelay: 50, // ms delay between chunks
    charDelay: 20,  // ms delay between chars within a chunk
  },
}
`,paraId:4},{value:"When both delays are ",paraId:5},{value:"0",paraId:5},{value:" (default), the processor ",paraId:5},{value:"skips setTimeout entirely",paraId:5},{value:" and pushes patches synchronously \u2014 the fastest path for ordinary production streaming.",paraId:5}]}}]);
