import React, { useEffect, useRef } from 'react';
import type { ChangeType, ChangelogCopy } from './data';

// Emoji per change type — leads each tag so releases scan at a glance while the
// chip itself stays uniform (on-brand: the emoji carries the color, not a second
// hue). Locale-independent; the text label beside it comes from `copy.types`.
const TYPE_EMOJI: Record<ChangeType, string> = {
  breaking: '💥',
  feature: '🆕',
  fix: '🐛',
  perf: '⚡️',
};

/**
 * One-shot entrance reveal for every timeline entry. Restrained like the
 * homepage's useReveal (opacity + small translateY, observed once then
 * detached), but observes all `.xmd-cl-entry` children of the list at once
 * instead of a single element. SSR-safe: entries render in their final position
 * by default and `is-in` is toggled client-side; reduced-motion users get them
 * revealed immediately with no transition.
 */
function useRevealChildren<T extends HTMLElement>(): React.RefObject<T> {
  const ref = useRef<T>(null);

  useEffect(() => {
    const root = ref.current;
    if (!root) return;
    const items = Array.from(root.querySelectorAll<HTMLElement>('.xmd-cl-entry'));
    if (items.length === 0) return;

    const reduce =
      typeof window.matchMedia === 'function' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    if (reduce || typeof IntersectionObserver === 'undefined') {
      items.forEach((el) => el.classList.add('is-in'));
      return;
    }

    const io = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-in');
            io.unobserve(entry.target);
          }
        }
      },
      { threshold: 0.12, rootMargin: '0px 0px -8% 0px' },
    );

    items.forEach((el) => io.observe(el));
    return () => io.disconnect();
  }, []);

  return ref;
}

/**
 * Changelog rendered as a single left-rail timeline: one continuous vertical
 * line down the left, a dot per release (the newest one accented), and the
 * version history to its right. Data is locale-driven via `copy` (see data.tsx).
 */
export default function ChangelogTimeline({ copy }: { copy: ChangelogCopy }) {
  const listRef = useRevealChildren<HTMLOListElement>();

  return (
    <div className="markdown">
      <main className="xmd-changelog">
        <header className="xmd-cl-hero">
          <h1>{copy.title}</h1>
          <p className="xmd-cl-subtitle">{copy.subtitle}</p>
        </header>

        <ol className="xmd-cl-list" ref={listRef}>
          {copy.releases.map((release, i) => (
            <li className="xmd-cl-entry xmd-reveal" key={release.version}>
              <span className="xmd-cl-marker" aria-hidden="true">
                <span className="xmd-cl-dot" />
              </span>
              <div className="xmd-cl-content">
                <div className="xmd-cl-meta">
                  <h2 className="xmd-cl-version">
                    {release.version}
                    {i === 0 && <span className="xmd-cl-latest">{copy.latest}</span>}
                  </h2>
                  <time className="xmd-cl-date">{release.date}</time>
                </div>
                <ul className="xmd-cl-changes">
                  {release.items.map((item, j) => (
                    <li className="xmd-cl-change" key={j}>
                      <span className={`xmd-cl-tag xmd-cl-tag--${item.type}`}>
                        <span className="xmd-cl-tag-emoji" aria-hidden="true">
                          {TYPE_EMOJI[item.type]}
                        </span>
                        {copy.types[item.type]}
                      </span>
                      {/* html is generated by build-changelog.mjs from our own
                          trusted CHANGELOG.md (escaped-then-re-tagged inline md). */}
                      <div className="xmd-cl-text">
                        <p dangerouslySetInnerHTML={{ __html: item.html }} />
                        {item.notes.length > 0 && (
                          <ul className="xmd-cl-notes">
                            {item.notes.map((note, k) => (
                              <li key={k} dangerouslySetInnerHTML={{ __html: note }} />
                            ))}
                          </ul>
                        )}
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </li>
          ))}
        </ol>
      </main>
    </div>
  );
}
